sudo: false
language: php
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - develop
  - "/\\d+\\.\\d+\\.\\d+?.*/"
php:
- 5.6
- 7.1
env:
  global:
  - GIT_COMMITTER_NAME=travis-ci
  - GIT_COMMITTER_EMAIL=inc@2inc.org
  - GIT_AUTHOR_NAME=travis-ci
  - GIT_AUTHOR_EMAIL=inc@2inc.org
  - WP_VERSION=latest WP_MULTISITE=0
cache:
  directories:
  - node_modules
  - vendor
  - "$HOME/.composer/cache"
install:
- nvm install 8
- npm install
- composer install
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
- composer test
before_deploy:
- npm run build
- npm run zip
- ls -la snow-monkey-member-post.zip
- export RELEASE_FILE=$(ls snow-monkey-member-post.zip)
deploy:
  provider: releases
  api_key:
    secure: Ef+bTkRcoL9Y+guJjZ9zuebZK1qljJNqIy52RMTAvKbotoOtPD8ye2BWtd5Litn+CfhCEj+F9X/HGwLBK+2yTmCWuxiAesyoKA5JxVx9fgfE7fXxYb89OzCyCtl0+KNqw3NwW0Py95lW1h4Yc699g5yrWhvYIJ7vMzqGiB4jBujvRyJUFPzqfIf2UaQotfd6QIZMLqT9OsMCNV+6rFT+kVHEtUmSz+tEorB1NzV9NHBQ8WTPlUeA7qakxkoNTvIS6kmY745+MuvItEKsDCOhUraw+NOChPLxPwfO1SxmOcJ7UXzjK4dr2SlnEJzt4eqHmrb5DVs3hUHV+ZFReOIHsRAOow6YCwSaC4KvDQZgvw0nePkl0g245Y0LA+yMBKRHuBfQhdhR9oIZ32l3YL4ebpmAf5nflcSKJ4Zl6i6ZHinrSTcyBlG91BHXgvj1TF+AyWdr50AWJM2B9b63KPjqekNWXX0lHimRfe5Hc7fvMpuoZLf4pDpW3peMnE0onMshQU4Ma+BtSzMWOFIHC28ZKcbBIyFZMxcxbDT3NglyKM2iWgMoMqBf/iUZjbw2P+KUXzyCBcv7equ9bRG7QU0iAYdhzlDXGuwerbo2eheodlu8g1L4hYKmK2OvtwqroXG08u253RTOHuwuvwq47dZuKZZNAJboIYY8vMk4QWksokM=
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  on:
    tags: true
    php: 7.1
    repo: inc2734/snow-monkey-member-post
